# Generated by Django 3.2.12 on 2023-11-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rocket', '0002_batch_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Students',
            new_name='Student',
        ),
    ]
